# Generated by Django 5.1.7 on 2025-10-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('title', models.CharField(max_length=150, verbose_name='Titre (ex: Développeur web)')),
                ('description', models.TextField(verbose_name='Description à propos de vous')),
                ('email', models.EmailField(max_length=254)),
                ('linkedin_url', models.URLField(blank=True, verbose_name='Lien LinkedIn')),
                ('github_url', models.URLField(blank=True, verbose_name='Lien GitHub')),
            ],
            options={
                'verbose_name': 'À propos',
                'verbose_name_plural': 'À propos',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du projet')),
                ('description', models.TextField(verbose_name='Description du projet')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('link', models.URLField(blank=True, verbose_name='Lien vers le projet (optionnel)')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-created_at'],
            },
        ),
    ]
