# Generated by Django 5.1.7 on 2025-10-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='techno',
            field=models.TextField(default='Non spécifié', verbose_name='Technologie utiliser'),
        ),
    ]
