# Generated by Django 5.1.7 on 2025-10-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_1', '0002_project_techno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='linkedin_url',
            field=models.URLField(blank=True, default='Non spécifié', verbose_name='Lien LinkedIn'),
        ),
    ]
