# Generated by Django 5.1.7 on 2025-10-18 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_1', '0004_exp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exp',
            options={'ordering': ['-created_at'], 'verbose_name': 'exp', 'verbose_name_plural': 'exps'},
        ),
    ]
