# Generated by Django 5.1.7 on 2025-10-18 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_1', '0005_alter_exp_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exp',
            options={},
        ),
    ]
